cache:
  paths:
    - .composer/

stages:
  - lint
  - test

variables:
  COMPOSER_CACHE_DIR: ".composer"
  COMPOSER_PROCESS_TIMEOUT: "1800"
  COMPOSER_ALLOW_SUPERUSER: "1"
  TYPO3_VERSION: ^8.7
  TYPO3_PATH_WEB: "$CI_PROJECT_DIR/.Build/Web"

.lint: &lint
  image: composer
  stage: lint
  before_script:
    - apk --no-cache add parallel
    - composer --no-ansi self-update
    - composer --no-ansi --version
    - composer require --no-interaction --no-ansi typo3/cms="${TYPO3_VERSION}"
    - composer install --no-interaction --no-ansi

lint:
  <<: *lint
  script:
    - find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

lint:cgl:
  <<: *lint
  script:
    - .Build/bin/php-cs-fixer fix --config=.php_cs -v --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $COMMIT_RANGE`

.test: &test
  stage: test
  services:
    - redis:latest
    - mysql:latest
  variables:
    MYSQL_DATABASE: "typo3"
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  before_script:
    - apk add --no-cache --virtual .build-deps autoconf g++ make
    - pecl install -f redis
    - docker-php-ext-install pdo pdo_mysql
    - docker-php-ext-enable redis
    - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php --no-ansi --install-dir=/usr/bin --filename=composer
    - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
    - composer require --no-interaction --no-ansi typo3/cms="${TYPO3_VERSION}"
    - composer install --no-interaction --no-ansi
  script:
    - >
      echo;
      echo "Running unit tests";
      .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml .Build/Web/typo3conf/ext/lock/Tests/Unit/

php56:t3_7:
  <<: *test
  image: php:5.6-alpine
  variables:
    TYPO3_VERSION: ^7.6

php70:t3_7:
  <<: *test
  image: php:7.0-alpine
  variables:
    TYPO3_VERSION: ^7.6

php70:t3_8:
  <<: *test
  image: php:7.0-alpine
  variables:
    TYPO3_VERSION: ^8.7

php71:t3_7:
  <<: *test
  image: php:7.1-alpine
  variables:
    TYPO3_VERSION: ^7.6

php71:t3_8:
  <<: *test
  image: php:7.1-alpine
  variables:
    TYPO3_VERSION: ^8.7
